
services:

  db-profesor:
    container_name: db-profesor
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=profesores
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

##base de datos alumnos
  db-alumnos:
    container_name: db-alumnos
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=alumnos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432



    ##base de datos materia

  db-materias:
    container_name: db-materias
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db-materias
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - 3306

 ## db inscripciones
  db-inscripciones:
    container_name: db-inscripciones
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db-inscripciones
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    expose:
      - 3307

  ### Zookeeper
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ### Kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.7.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1